### ISSUE TITLE
Server crashes with VanillaConfig installed

### ISSUE THREAD

**Issue by GitUser14975** [Tre5et/vanillaconfig#1]
Hello, I'm the owner of the [Another RPG Modpack](https://www.curseforge.com/minecraft/modpacks/another-rpg-pack) and I've been recently getting some complains from my players that servers wouldn't run and would crash immediately if VanillaConfig & RideHud are installed. Here's some info from one of my players who experienced it:

```
I'm using server pack v4.1.2, and Fabric server version 0.14.22.

I placed the config and mods folders into a freshly made server, the server does not run, it crashes with the following error:

-----------------

[18:31:52] [main/ERROR]: Failed to start the minecraft server[18:31:52] [main/ERROR]: Failed to start the minecraft 
serverjava.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'vanillaconfig'! at 
net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.22.jar:?] at 
net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.22.jar:?] at 
net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.22.jar:?] at 
net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.22.jar:?] at
net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.22.jar:?] at 
net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?] at 
net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?] at 
net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.22.jar:?] at 
net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.22.jar:?]Caused 
by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents in environment 
type SERVER at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-
0.14.22.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~
[fabric-loader-0.14.22.jar:?] at 
net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-
0.14.22.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-
0.14.22.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-
0.14.22.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?] 
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] at 
net.treset.vanillaconfig.config.managers.SaveLoadManager.init(SaveLoadManager.java:15) ~[vanillaconfig-1.2.7+1.20.jar:?] at 
net.treset.vanillaconfig.VanillaConfigMod.onInitialize(VanillaConfigMod.java:13) ~[vanillaconfig-1.2.7+1.20.jar:?] at 
net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?] ... 7 more`

**Comment by Tre5et** [comment]
Running the mod in a server environment is not supported, it is client only.
I have now made sure the mod is disabled when running in a server environment so that it doesn't cause this crash anymore.
This change is in version 1.2.9 for 1.20.2.
Since this modpack isn't updated to 1.20.2 yet, I have attached a build for 1.20 and 1.20.1 that implements this fix.
[vanillaconfig-1.2.7+1.20-server-crash-fix.zip](https://github.com/Tre5et/vanillaconfig/files/13180615/vanillaconfig-1.2.7%2B1.20-server-crash-fix.zip)
